"""
Short-PHD detector implementation for unified interface.

This detector wraps the Short-PHD method that uses Persistent Homology
Dimensionality (PHD) with off-topic prompt augmentation to detect
AI-generated short text via topological data analysis.

Reference: https://github.com/djwei96/ShortPHD
"""

import os
import random
import sys
from pathlib import Path
from typing import Dict, List, Union

import numpy as np

from omini_text.detectors import BaseDetector

# Add baseline/ShortPHD to Python path
short_phd_path = Path(__file__).parent.parent.parent / "baseline" / "ShortPHD"
sys.path.insert(0, str(short_phd_path))


# 12 detection prompts from the paper
DETECTION_PROMPTS = [
    "Identifying text generated by large language models (LLMs) like GPT can be challenging, but there are some strategies and telltale signs that can help. Here are some suggestions: Repetition and Redundancy and Overly Polished or Generic Language. ",
    "LLM-generated text may contain repetitive phrases or ideas. Although models are improving, they might still circle back to the same points or restate them in slightly different ways. ",
    "LLMs often produce text that is well-structured and free from obvious errors, sometimes appearing overly polished. The language may also be somewhat generic, lacking the nuance, style, or personal touch that a human writer might include. ",
    "The tone or style of LLM-generated text might fluctuate unexpectedly. For instance, a paragraph may shift from formal to informal language or from being highly detailed to overly vague. ",
    "While LLMs are generally accurate, they can make mistakes that are unusual for humans, such as misinterpreting context, creating fictional facts, or making nonsensical statements. ",
    "LLMs can generate text that seems insightful but lacks true depth. The text may superficially address a topic without providing meaningful analysis or understanding. ",
    "The phrasing in LLM-generated text might sound slightly off, either too formal or too casual, or use uncommon word combinations that a human writer might not choose. ",
    "LLMs might draw connections between ideas that don't logically follow from each other. This can result in text that feels disjointed or where the flow of argument is not clear. ",
    "Some LLMs may overuse certain phrases or sentence structures, especially ones that were prominent in their training data. ",
    "Use AI detection tools designed to identify LLM-generated content. These tools analyze patterns in the text to predict whether it was written by a human or a machine. ",
    "LLMs may provide inconsistent answers when asked the same question in different ways. A human writer is more likely to maintain consistent opinions or facts across different contexts. ",
    "Using a combination of these strategies can help you more reliably identify LLM-generated text, although it\u2019s worth noting that as AI models improve, the distinction between human and machine-generated text is becoming increasingly subtle. ",
]

MIN_SUBSAMPLE = 40
INTERMEDIATE_POINTS = 7


class ShortPHDDetector(BaseDetector):
    """
    Short-PHD detector for AI-generated short text detection.

    Uses Persistent Homology Dimensionality (PHD) with 12 off-topic prompt
    augmentations to detect AI-generated text via topological analysis of
    token embedding point clouds.

    Higher PHD score = more likely AI-generated.
    """

    def __init__(self, config: Dict):
        """
        Initialize Short-PHD detector.

        Args:
            config: Configuration dictionary with parameters:
                - base_lm_name: Base language model (default: meta-llama/Meta-Llama-3-8B-Instruct)
                - cache_dir: Model cache directory (default: ./cache)
                - max_length: Max tokenization length (default: 1000)
                - truncation_length: Truncate text to N tokens, None to skip (default: None)
                - threshold: Classification threshold (default: 15.0)
                - device: CUDA device string (default: "0")
                - seed: Random seed (default: 42)
        """
        super().__init__(config)

        import torch
        from transformers import AutoModel, AutoTokenizer

        base_lm_name = config.get(
            "base_lm_name", "meta-llama/Meta-Llama-3-8B-Instruct"
        )
        cache_dir = config.get(
            "cache_dir", str(Path(__file__).parent.parent.parent / "cache")
        )
        device_str = config.get("device", "0")
        seed = config.get("seed", 42)

        self.max_length = config.get("max_length", 1000)
        self.truncation_length = config.get("truncation_length", None)
        self.threshold = config.get("threshold", 15.0)

        # Set random seeds
        random.seed(seed)
        np.random.seed(seed)
        torch.manual_seed(seed)
        torch.cuda.manual_seed(seed)
        torch.cuda.manual_seed_all(seed)
        os.environ["PYTHONHASHSEED"] = str(seed)

        print(f"\nInitializing Short-PHD Detector")
        print(f"   Base LM: {base_lm_name}")
        print(f"   Truncation: {self.truncation_length or 'None (use full text)'}")
        print(f"   Threshold: {self.threshold}")
        print(f"   Device: cuda:{device_str}\n")

        # Load model and tokenizer
        self.device = (
            torch.device(f"cuda:{device_str}")
            if torch.cuda.is_available()
            else torch.device("cpu")
        )
        self.tokenizer = AutoTokenizer.from_pretrained(
            base_lm_name, cache_dir=cache_dir
        )
        self.model = AutoModel.from_pretrained(base_lm_name, cache_dir=cache_dir)
        self.model.to(self.device)
        self.model.eval()

        # Initialize PHD solver
        from utils import PHD

        self.solver = PHD(alpha=1.0, metric="euclidean", n_points=9)

    def _compute_phd(self, text: str, prompt_number: int = 0) -> float:
        """Compute PHD for a single text using the base model embeddings."""
        import torch

        inputs = self.tokenizer(
            text,
            truncation=True,
            max_length=self.max_length + 2,
            return_tensors="pt",
        ).to(self.device)

        with torch.no_grad():
            outp = self.model(**inputs)

        # Remove CLS token, then skip prompt_number+1 tokens
        embeddings = outp[0][0].cpu().numpy()[1:]
        embeddings = embeddings[prompt_number + 1 :]

        mx_points = embeddings.shape[0]
        mn_points = MIN_SUBSAMPLE
        step = (mx_points - mn_points) // INTERMEDIATE_POINTS

        if step <= 0 or mx_points <= mn_points:
            # Text too short for reliable PHD computation
            return float("nan")

        return self.solver.fit_transform(
            embeddings,
            min_points=mn_points,
            max_points=mx_points - step,
            point_jump=step,
        )

    def _truncate_text(self, text: str) -> str:
        """Truncate text to truncation_length tokens."""
        if self.truncation_length is None:
            return text
        tokens = self.tokenizer.tokenize(text)
        tokens = tokens[: self.truncation_length]
        return self.tokenizer.convert_tokens_to_string(tokens)

    def _detect_single(self, text: str) -> Dict:
        """Detect single text using prompt-augmented Short-PHD."""
        import math

        # Optionally truncate
        text = self._truncate_text(text)

        # Compute PHD for each of the 12 prompts
        dim_prompts = []
        for prompt in DETECTION_PROMPTS:
            combined_text = prompt + text
            dim = self._compute_phd(combined_text, prompt_number=0)
            if not math.isnan(dim):
                dim_prompts.append(dim)

        # Average across valid prompt scores
        if dim_prompts:
            score = float(np.mean(dim_prompts))
        else:
            score = 0.0

        label = 1 if score >= self.threshold else 0

        return {
            "text": text,
            "label": label,
            "score": score,
            "metadata": {
                "dim_prompts": [float(d) for d in dim_prompts],
                "num_valid_prompts": len(dim_prompts),
                "threshold": self.threshold,
            },
        }

    def detect(self, text: Union[str, List[str]]) -> Union[Dict, List[Dict]]:
        """
        Detect if text is AI-generated using Short-PHD.

        Args:
            text: Input text or list of texts

        Returns:
            Result dict or list of dicts with keys:
            - text: Input text
            - label: 0=human, 1=AI-generated
            - score: Mean PHD across 12 prompt augmentations (higher = more AI)
            - metadata: Per-prompt PHD scores and threshold
        """
        if isinstance(text, list):
            return [self._detect_single(t) for t in text]
        return self._detect_single(text)

    def cleanup(self):
        """Release GPU memory."""
        import gc

        import torch

        if hasattr(self, "model") and self.model is not None:
            del self.model
            self.model = None
        if hasattr(self, "tokenizer") and self.tokenizer is not None:
            del self.tokenizer
            self.tokenizer = None
        if hasattr(self, "solver"):
            del self.solver
            self.solver = None

        gc.collect()
        if torch.cuda.is_available():
            torch.cuda.empty_cache()

        print("Short-PHD detector cleaned up, GPU memory released")
